---
- name: Ensure configuration directories exist.
  file:
    path: "{{ item }}"
    state: directory
    follow: true
  with_items:
    - "{{ php_conf_path }}"
    - "{{ php_extension_conf_path }}"

- name: Place PHP configuration file in place.
  template:
    src: php.ini.j2
    dest: "{{ php_conf_path }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify: restart webserver
  when: php_use_managed_ini
  with_items:
    - "php.ini"

- name: Place PHP CLI configuration file in place.
  template:
    src: php.ini.j2
    dest: "/etc/php5/cli/php.ini"
    owner: root
    group: root
    mode: 0644
  notify: restart webserver
  when: php_use_managed_ini

- name: Changing php umask
  lineinfile: dest=/etc/init/php5-fpm.conf line="umask 0002"
  when: php_enable_php_fpm

- name: Place PHP configuration file in place for php-fpm.
  template:
    src: php.ini.j2
    dest: "{{ php_conf_path }}/fpm/php.ini"
    owner: root
    group: root
    mode: 0644
  notify: restart webserver
  when: php_use_managed_ini and php_enable_php_fpm


- name: Place APC configuration file in place.
  template:
    src: apc.ini.j2
    dest: "{{ php_extension_conf_path }}/{{ php_apc_conf_filename }}"
    owner: root
    group: root
    force: yes
    mode: 0644
  when: php_enable_apc
  notify: restart webserver

- name: Place OpCache configuration file in place.
  template:
    src: opcache.ini.j2
    dest: "{{ php_extension_conf_path }}/{{ php_opcache_conf_filename }}"
    owner: root
    group: root
    force: yes
    mode: 0644
  when: php_opcache_enable
  notify: restart webserver

- name: Delete default pool
  file: path={{ php_conf_path }}/fpm/pool.d/www.conf state=absent
  when: php_enable_php_fpm
  notify:
   - restart webserver

- name: Copy the POOL configurations
  template: >
    src=pool.conf.j2
    dest={{ php_conf_path }}/fpm/pool.d/{{ item['name'] }}.conf
    backup=yes
  with_items: "{{ php_fpm_pools }}"
  when: php_fpm_pools|lower != 'none' and php_enable_php_fpm
  notify:
   - restart webserver

- name: Ensure php-fpm is restarted and enabled at boot (if configured).
  service:
    name: "{{ php_fpm_daemon }}"
    state: restarted
    enabled: yes
  when: php_enable_php_fpm
