- name: Setting reopenlogs path
  set_fact:
    fpm_reopenlogs_path: /usr/lib/php5/php5-fpm-reopenlogs
  when: php_version_to_install == 5 and fpm_reopenlogs_path is not defined

- name: Setting reopenlogs path
  set_fact:
    fpm_reopenlogs_path: "/usr/lib/php/php{{ php_version_to_install }}-fpm-reopenlogs"
  when: php_version_to_install > 5 and fpm_reopenlogs_path is not defined

- name: Check that fpm_reopenlogs_path exist.
  stat:
    path: "{{ fpm_reopenlogs_path }}"
  register: _reopenlog

- name: If reopenlogs doesn't exist
  fail:
    msg: "You have defined php_slowlog_path, who require valid path fpm_reopenlogs_path for logrotate"
  when: not _reopenlog.stat.exists

- name: Configure logrotate for php slowlog
  template:
    src: logrotate-slowlog.conf.j2
    dest: /etc/logrotate.d/php-slowlog.conf
  tags:
    - logrotate
  when: php_slowlog_path is defined and php_slowlog_path
