---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define php_packages.
  set_fact:
    php_packages: "{{ __php_packages | list }}"
  when: php_packages is not defined

- name: Define php_webserver_daemon.
  set_fact:
    php_webserver_daemon: "{{ __php_webserver_daemon }}"
  when: php_webserver_daemon is not defined

- name: Define php_fpm_daemon.
  set_fact:
    php_fpm_daemon: "{{ __php_fpm_daemon }}"
  when: php_fpm_daemon is not defined

# If we are on a debian and php 5
- name: Setting __php_conf_path (Debian, PHP5)
  set_fact:
    __php_conf_path: >
      "{{ '/etc/php{{ php_version_to_install }}' if php_webserver_daemon
      and php_webserver_daemon != 'apache2' else '/etc/php{{ php_version_to_install }}/apache2' }}"
  when: ansible_os_family == 'Debian' and php_version_to_install == 5

# If we are on a debian and php > 5
- name: Setting __php_conf_path (Debian, PHP>5)
  set_fact:
    __php_conf_path: >
      "{{ '/etc/php/{{ php_version_to_install }}' if php_webserver_daemon and
      php_webserver_daemon != 'apache2' else '/etc/php{{ php_version_to_install }}/apache2' }}"
  when: ansible_os_family == 'Debian' and php_version_to_install != 5

- name: Define php_conf_path.
  set_fact:
    php_conf_path: "{{ __php_conf_path }}"
  when: php_conf_path is not defined

- name: Define php_extension_conf_paths.
  set_fact:
    php_extension_conf_paths: "{{ __php_extension_conf_paths }}"
  when: php_extension_conf_paths is not defined

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Check the installed version of PHP.
  shell: '{{ php_executable }} -r "echo PHP_VERSION;"'
  register: php_version
  changed_when: false
  check_mode: no

- name: Disable opcache if PHP version is < 5.5.
  set_fact:
    php_opcache_enable: 0
  when: "php_version.stdout.split('.')[0] == '5' and php_version.stdout.split('.')[1] < '5'"

# Configure PHP.
- include: configure.yml

# Configure AWS Elasticache.
- include: aws-elasticache.yml
  when: php_aws_elasticache


# Configure Logrotate
- include: logrotate.yml
  when: php_enable_php_fpm
