---
- name: Add repository key
  apt_key:
    url: "{{ php_debian_pkg_key }}"
    state: present
  when: php_debian_pkg_managed and php_debian_pkg_key

- name: Install repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  when: php_debian_pkg_managed and php_debian_pkg_name
  with_items: "{{ php_debian_pkg_name }}"

- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 86400
  ignore_errors: yes

- name: Ensure PHP packages are installed.
  apt:
    name: "{{ php_packages }}"
    state: "{{ apt_install_policy }}"
  notify: restart webserver
